version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # - ./initdb.d:/docker-entrypoint-initdb.d
    restart: always
    tty: true
volumes:
  dbdata:
